### ISSUE TITLE
cv::findFundamentalMat error (Bad argument)

### ISSUE THREAD

**Issue by Phuong-DoNgocBinh-2210** [agarciamontoro/image-rectification#4]
Hi.
I am using your src with VS2015 and OpenCV 3.4.3. However, the code break at line 135 of util.cpp. Termial show this line:
_**OpenCV(3.4.3) Error: Bad argument (The input arrays should be 2D or 3D point sets) in cv::findFundamentalMat, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\calib3d\src\fundam.cpp, line 782**_

What do you think would be the matter? Thanks

**Comment by Phuong-DoNgocBinh-2210** [comment]
![image](https://user-images.githubusercontent.com/31609976/46515872-9c6c7700-c890-11e8-81e4-dac163510746.png)
This is how it looks like in my vs2015

**Comment by agarciamontoro** [comment]
I know nothing about Visual Studio, I cannot help you there.

About OpenCV: this is an old project in which we used OpenCV 2, not 3. However, I've taken a look to the docs of `findFundamentalMat` in both [version 2](https://docs.opencv.org/2.4.13.6/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html?highlight=findfundamentalmat#Mat%20findFundamentalMat(InputArray%20points1,%20InputArray%20points2,%20int%20method,%20double%20param1,%20double%20param2,%20OutputArray%20mask)) and [version 3](https://docs.opencv.org/3.4.3/d9/d0c/group__calib3d.html#gae420abc34eaa03d0c6a67359609d8429) and I don't find any differences between them.

And the input arrays are indeed 2D points: see [line 120 of util.cpp](https://github.com/agarciamontoro/image-rectification/blob/master/src/util.cpp#L120).

**Comment by Phuong-DoNgocBinh-2210** [comment]
> I know nothing about Visual Studio, I cannot help you there.
> 
> About OpenCV: this is an old project in which we used OpenCV 2, not 3. However, I've taken a look to the docs of `findFundamentalMat` in both [version 2](https://docs.opencv.org/2.4.13.6/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html?highlight=findfundamentalmat#Mat%20findFundamentalMat(InputArray%20points1,%20InputArray%20points2,%20int%20method,%20double%20param1,%20double%20param2,%20OutputArray%20mask)) and [version 3](https://docs.opencv.org/3.4.3/d9/d0c/group__calib3d.html#gae420abc34eaa03d0c6a67359609d8429) and I don't find any differences between them.
> 
> And the input arrays are indeed 2D points: see [line 120 of util.cpp](https://github.com/agarciamontoro/image-rectification/blob/master/src/util.cpp#L120).

Hi, 
Thank you for your support. If so, can you please help to confirm which IDE you used for your project to run the C++ code?

**Comment by 29antonioac** [comment]
Hi,

we didn't use any IDE, we coded this with Atom and compiled with g++ under some Archlinux systems.

**Comment by Phuong-DoNgocBinh-2210** [comment]
I see, thank you. I will close this issue. Cheers!

**Comment by Phuong-DoNgocBinh-2210** [comment]
Hi, 
Sorry to reopen the issue because after having some research on the code. I don't understand a few points below. I am doing a thesis on Photogrammetry, therefore, your project would help me a lot if I can understand your code:
--> When I compile the code, it stucks at: F = findFundamentalMat(first, second, flag,1., 0.99, mask ); line 135 of util.cpp.
-->According to the error: Bad argument  (The input arrays should be 2D or 3D point sets). I believe in the line 135, parameter "first", and "second" is not a 2D/3D point sets.  Looking further into the code, I saw that "first" and "second" are defined that (line 123 - 132):
`
if (good_matches_1.empty() && good_matches_2.empty()){
      matches = match(one, other, descriptor_id::BRUTE_FORCE, detector_id::BRISK);
      first = matches.first;
      second = matches.second;
      flag |= CV_FM_RANSAC;
    }
    else{
      first = good_matches_1;
      second = good_matches_2;
    }
`
--> However, I cannot figure out what is the purpose of "good_matches", and where you calculated the "good_matches" in your code. Can you please help me on this.
Thank you,

**Comment by 29antonioac** [comment]
Hi!

good_matches refers to matches previously obtained using a BFMatcher or FlannBasedMatcher (although any matcher should work). If they are empty (which is the usual case) , they are calculated in the (see [match function](https://github.com/agarciamontoro/image-rectification/blob/0c40310bca58ea430952548a42333a18b2d0453b/src/util.cpp#L155), which returns a pair of vector<Point2d>,vector<Point2d>. 

As the [doc](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#Mat%20findFundamentalMat(InputArray%20points1,%20InputArray%20points2,%20int%20method,%20double%20param1,%20double%20param2,%20OutputArray%20mask)) says a vector should be a valid source of points, so I don't know what could be the problem...

**Comment by Phuong-DoNgocBinh-2210** [comment]
I found the issue, I did not link the correct path of the img file in the main.cpp:
-->Mat img_1 = imread("C:\\C++\\Rectify\\img\\perra_7.jpg");
That is why the error for bad argument since it was 0.
Problem solve. And close issue. Thank you.
