### ISSUE TITLE
Error: Assertion failed in OpenCV(3.4.3) - opencv2\core\mat.inl.hpp, line 1101

### ISSUE THREAD

**Issue by Phuong-DoNgocBinh-2210** [agarciamontoro/image-rectification#5]
Hi,
I have an error like this: 
_--> OpenCV(3.4.3) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file c:\opencv-3.4.3\build\include\opencv2\core\mat.inl.hpp, line 1101_

And looking into the line 1101 I see ".at" of Mat to be concerned:
__template<typename _Tp> inline
_Tp& Mat::at(int i0, int i1)
{
    CV_DbgAssert(dims <= 2);
    CV_DbgAssert(data);
    CV_DbgAssert((unsigned)i0 < (unsigned)size.p[0]);
    CV_DbgAssert((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())); //This is Line 1101
    CV_DbgAssert(CV_ELEM_SIZE1(traits::Depth<_Tp>::value) == elemSize1());
    return ((_Tp*)(data + step.p[0] * i0))[i1];
}_

Then, I have a look at your main.cpp code (line 58 to 96), you are using this Mat::at a lot. I think the error might be in the conflict of data type. Can you give some advice? Thanks

**Comment by Phuong-DoNgocBinh-2210** [comment]
I have read this post: https://docs.opencv.org/trunk/d3/d63/classcv_1_1Mat.html#aa5d20fc86d41d59e4d71ae93daee9726
The OP said that: If matrix is of type CV_64F then use Mat.at double (y,x).
--> So from line 58 to 96, you are right when using double, no data type conflict here. But then, I cannot undertand why it threw me an exception here?

**Comment by Phuong-DoNgocBinh-2210** [comment]
Hi, 
I have successfully debugged. 
Please check again file "util.cpp". Line 61-63. By solving the equation for Fe = 0. You have the matrix "e" with the dim is (3x1). But the way you assigned to epipole, you treated the result as matrix (1x3). That's why it goes out of bound and shows the above issue. Please update to (0,0), (1,0), and (2,0) respectively!

**Comment by 29antonioac** [comment]
Thanks for finding the issue. I have push that change.

Hope this project helps you!

**Comment by agarciamontoro** [comment]
Thanks to both of you! @judalucifer, feel free to open a pull request if you find anything else!

I'm closing this issue as I guess this is already solved, but reopen it if the bug is still there :)
